### ISSUE TITLE
Breaks with ipfs ^0.48.0

### ISSUE THREAD

**Issue by DotCoyote** [ipfs-shipyard/ipfs-provider#22]
I just upgraded my local ipfs dependency to `0.48.1` and now I get these 2 errors:

**Code:**

```javascript
    const { ipfs } = await getIpfs({
      providers: [
        providers.jsIpfs({
          loadJsIpfsModule: () => import('ipfs'),
          options: defaultNodeOptions,
        }),
      ],
    });
```

**Console errors:**

```
[ipfs-provider] NotInitializedRepoError: Repo in path ipfs is not initialized!
    at Object.getVersion (webpack-internal:///./node_modules/ipfs/node_modules/ipfs-repo-migrations/src/repo/version.js:24:11)
    at async Object.migrate (webpack-internal:///./node_modules/ipfs/node_modules/ipfs-repo-migrations/src/index.js:64:26)
    at async IpfsRepo.open (webpack-internal:///./node_modules/ipfs/node_modules/ipfs-repo/src/index.js:128:11)
    at async Proxy.init (webpack-internal:///./node_modules/ipfs/src/core/components/init.js:62:9)
    at async Object.create (webpack-internal:///./node_modules/ipfs/src/core/index.js:55:3)
    at async tryJsIpfs (webpack-internal:///./node_modules/ipfs-provider/src/providers/js-ipfs.js:13:16)
    at async getIpfs (webpack-internal:///./node_modules/ipfs-provider/src/index.js:52:19)

App.vue?ec60:101 TypeError: Cannot read property 'ipfs' of undefined
    at _callee3$ (ipfs.hook.ts?cf80:37)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
```

Also, when following your documentation and use this:

```javascript
    const result = await getIpfs({
      providers: [
        jsIpfs({
          // eslint-disable-next-line global-require
          loadJsIpfsModule: () => require('ipfs'),
          options: defaultNodeOptions,
        }),
      ],
    });
```

I get this pointing to L2 (`providers: [`) 

```
TypeError: Object(...) is not a function
    at _callee3$ (ipfs.hook.ts?cf80:38)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
```

**Comment by DotCoyote** [comment]
Nevermind, deleting browser-cache did the trick...
